# Generated by Django 5.2.5 on 2025-11-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='faculty',
            new_name='user',
        ),
    ]
