# Generated by Django 5.2.5 on 2025-11-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_faculty_attendancerecord_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='user',
            new_name='faculty',
        ),
    ]
